version: '3.8'

services:
  locust:
    image: locustio/locust:2.15.1
    volumes:
      - ./tests/test_load:/mnt/locust
    ports:
      - "8089:8089"
    command: -f /mnt/locust/locustfile.py --host=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"