global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Pour Windows/Mac
        # - targets: ['app:8000']  # Pour Linux

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']